=== DennyGD/Databases/XmlBasics/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students" type="studentsType"/>
  <xs:complexType name="studentType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="birthDate">
        <xs:simpleType>
          <xs:restriction base="xs:date">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="gender">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Female"/>
            <xs:enumeration value="Male"/>
            <xs:enumeration value="Other"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="phone">
        <xs:simpleType>
          <xs:restriction base="xs:long">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="email">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:byte" name="course"/>
      <xs:element type="xs:string" name="specialty"/>
      <xs:element name="facultyNumber">
        <xs:simpleType>
          <xs:restriction base="xs:short">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="endorsements">
        <xs:simpleType>
          <xs:restriction base="xs:byte">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="examsType" name="exams"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="examsType">
    <xs:sequence>
      <xs:element type="examType" name="exam" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="examType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="tutor">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="score">
        <xs:simpleType>
          <xs:restriction base="xs:float">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="studentsType">
    <xs:sequence>
      <xs:element type="studentType" name="student" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== DennyGD/Databases/XmlBasics/students.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students xmlns:students="urn:students"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="students.xsd">
    <student>
        <name>Jane</name>
        <birthDate>1988-06-06</birthDate>
        <gender>Female</gender>
        <phone>35900886123456</phone>
        <email>janeDoe@gmail.com</email>
        <course>1</course>
        <specialty>History</specialty>
        <facultyNumber>001234</facultyNumber>
        <endorsements>2</endorsements>
        <exams>
            <exam>
                <name>Exam 1</name>
                <tutor>Prof</tutor>
                <score>6</score>
            </exam>
            <exam>
                <name>Exam 3</name>
                <tutor>Another prof</tutor>
                <score>5.5</score>
            </exam>
        </exams>
    </student>
    <student>
        <name>John</name>
        <birthDate>1988-05-05</birthDate>
        <gender>Male</gender>
        <phone>35900886123457</phone>
        <email>johnDoe@gmail.com</email>
        <course>1</course>
        <specialty>History</specialty>
        <facultyNumber>001235</facultyNumber>
        <endorsements>3</endorsements>
        <exams>
            <exam>
                <name>Exam 5</name>
                <tutor>Prof</tutor>
                <score>4</score>
            </exam>
            <exam>
                <name>Exam 2</name>
                <tutor>Prof</tutor>
                <score>5.5</score>
            </exam>
        </exams>
    </student>
</students>
